config/routes.rb
Rails.application.routes.draw do
  resources :inquiries
  devise_for :users

  resources :services
  resources :helpers
  resources :users

  root 'top#index'

end

app/controllers/helpers_controller.rb
class HelpersController < ApplicationController
  before_action :set_helper, only: [:show, :edit, :update, :destroy]

  # GET /helpers
  # GET /helpers.json
  def index
    @helpers = Helper.all
  end

  # GET /helpers/1
  # GET /helpers/1.json
  def show
  end

  # GET /helpers/new
  def new
    @helper = Helper.new
  end

  # GET /helpers/1/edit
  def edit
  end

  # POST /helpers
  # POST /helpers.json
  def create
    @helper = Helper.new(helper_params)

    respond_to do |format|
      if @helper.save
        format.html { redirect_to @helper, notice: 'Helper was successfully created.' }
        format.json { render :show, status: :created, location: @helper }
      else
        format.html { render :new }
        format.json { render json: @helper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /helpers/1
  # PATCH/PUT /helpers/1.json
  def update
    respond_to do |format|
      if @helper.update(helper_params)
        format.html { redirect_to @helper, notice: 'Helper was successfully updated.' }
        format.json { render :show, status: :ok, location: @helper }
      else
        format.html { render :edit }
        format.json { render json: @helper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /helpers/1
  # DELETE /helpers/1.json
  def destroy
    @helper.destroy
    respond_to do |format|
      format.html { redirect_to helpers_url, notice: 'Helper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_helper
      @helper = Helper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def helper_params
      params.require(:helper).permit(:name, :district, :time, :urgent, :old, :hobby, :selfintoroduction, :personality, :raisingchild, :keepdog, :cook)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/helpers_helper.rb
module HelpersHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/helpers/_form.html.erb
<%= form_for(@helper) do |f| %>
  <% if @helper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@helper.errors.count, "error") %> prohibited this helper from being saved:</h2>

      <ul>
      <% @helper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :district %><br>
    <%= f.text_field :district %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :urgent %><br>
    <%= f.check_box :urgent %>
  </div>
  <div class="field">
    <%= f.label :old %><br>
    <%= f.number_field :old %>
  </div>
  <div class="field">
    <%= f.label :hobby %><br>
    <%= f.text_area :hobby %>
  </div>
  <div class="field">
    <%= f.label :selfintoroduction %><br>
    <%= f.text_area :selfintoroduction %>
  </div>
  <div class="field">
    <%= f.label :personality %><br>
    <%= f.text_area :personality %>
  </div>
  <div class="field">
    <%= f.label :raisingchild %><br>
    <%= f.text_area :raisingchild %>
  </div>
  <div class="field">
    <%= f.label :keepdog %><br>
    <%= f.text_area :keepdog %>
  </div>
  <div class="field">
    <%= f.label :cook %><br>
    <%= f.text_area :cook %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/helpers/edit.html.erb
<h1>Editing Helper</h1>

<%= render 'form' %>

<%= link_to 'Show', @helper %> |
<%= link_to 'Back', helpers_path %>

app/views/helpers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Helpers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>District</th>
      <th>Time</th>
      <th>Urgent</th>
      <th>Old</th>
      <th>Hobby</th>
      <th>Selfintoroduction</th>
      <th>Personality</th>
      <th>Raisingchild</th>
      <th>Keepdog</th>
      <th>Cook</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @helpers.each do |helper| %>
      <tr>
        <td><%= helper.name %></td>
        <td><%= helper.district %></td>
        <td><%= helper.time %></td>
        <td><%= helper.urgent %></td>
        <td><%= helper.old %></td>
        <td><%= helper.hobby %></td>
        <td><%= helper.selfintoroduction %></td>
        <td><%= helper.personality %></td>
        <td><%= helper.raisingchild %></td>
        <td><%= helper.keepdog %></td>
        <td><%= helper.cook %></td>
        <td><%= link_to 'Show', helper %></td>
        <td><%= link_to 'Edit', edit_helper_path(helper) %></td>
        <td><%= link_to 'Destroy', helper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Helper', new_helper_path %>

app/views/helpers/new.html.erb
<h1>New Helper</h1>

<%= render 'form' %>

<%= link_to 'Back', helpers_path %>

app/views/helpers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @helper.name %>
</p>

<p>
  <strong>District:</strong>
  <%= @helper.district %>
</p>

<p>
  <strong>Time:</strong>
  <%= @helper.time %>
</p>

<p>
  <strong>Urgent:</strong>
  <%= @helper.urgent %>
</p>

<p>
  <strong>Old:</strong>
  <%= @helper.old %>
</p>

<p>
  <strong>Hobby:</strong>
  <%= @helper.hobby %>
</p>

<p>
  <strong>Selfintoroduction:</strong>
  <%= @helper.selfintoroduction %>
</p>

<p>
  <strong>Personality:</strong>
  <%= @helper.personality %>
</p>

<p>
  <strong>Raisingchild:</strong>
  <%= @helper.raisingchild %>
</p>

<p>
  <strong>Keepdog:</strong>
  <%= @helper.keepdog %>
</p>

<p>
  <strong>Cook:</strong>
  <%= @helper.cook %>
</p>

<%= link_to 'Edit', edit_helper_path(@helper) %> |
<%= link_to 'Back', helpers_path %>