config/routes.rb
Rails.application.routes.draw do
  resources :inquiries
  devise_for :users

  resources :services
  resources :helpers
  resources :users

  root 'top#index'

end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :set_inquiry, only: [:show, :edit, :update, :destroy]

  # GET /inquiries
  # GET /inquiries.json
  def index
    @inquiries = Inquiry.all
  end

  # GET /inquiries/1
  # GET /inquiries/1.json
  def show
  end

  # GET /inquiries/new
  def new
    @inquiry = Inquiry.new
  end

  # GET /inquiries/1/edit
  def edit
  end

  # POST /inquiries
  # POST /inquiries.json
  def create
    @inquiry = Inquiry.new(inquiry_params)

    respond_to do |format|
      if @inquiry.save
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully created.' }
        format.json { render :show, status: :created, location: @inquiry }
      else
        format.html { render :new }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inquiries/1
  # PATCH/PUT /inquiries/1.json
  def update
    respond_to do |format|
      if @inquiry.update(inquiry_params)
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @inquiry }
      else
        format.html { render :edit }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inquiries/1
  # DELETE /inquiries/1.json
  def destroy
    @inquiry.destroy
    respond_to do |format|
      format.html { redirect_to inquiries_url, notice: 'Inquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inquiry
      @inquiry = Inquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inquiry_params
      params.require(:inquiry).permit(:name, :email, :content)
    end
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/inquiries/_form.html.erb
<%= form_for(@inquiry) do |f| %>
  <% if @inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>

      <ul>
      <% @inquiry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :名前 %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :内容 %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inquiries/edit.html.erb
<h1>Editing Inquiry</h1>

<%= render 'form' %>

<%= link_to 'Show', @inquiry %> |
<%= link_to 'Back', inquiries_path %>

app/views/inquiries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>お問い合わせ</h1>

<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>Email</th>
      <th>内容</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inquiries.each do |inquiry| %>
      <tr>
        <td><%= inquiry.name %></td>
        <td><%= inquiry.email %></td>
        <td><%= inquiry.content %></td>
        <td><%= link_to 'Show', inquiry %></td>
        <td><%= link_to 'Edit', edit_inquiry_path(inquiry) %></td>
        <td><%= link_to 'Destroy', inquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'お問い合わせ投稿', new_inquiry_path %>

app/views/inquiries/new.html.erb
<h1>お問い合わせ投稿</h1>

<%= render 'form' %>

<%= link_to 'Back', inquiries_path %>

app/views/inquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @inquiry.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @inquiry.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @inquiry.content %>
</p>

<%= link_to 'Edit', edit_inquiry_path(@inquiry) %> |
<%= link_to 'Back', inquiries_path %>